keys:
  pgp:
  - &ccat3z A784DBF88D718B5FA46CF254040BD409F274BE67
  age:
  - &laptop-0 age1r57j4k3lgyzs73vklxu3vkf4w06f3q6h5f5f5zk2qx26mw0q2dps4shanr
  - &pc-0 age107awdyvh40y48gjzsvnf63ev4hzj0sgpl8x4ryfzw582qkznx53smffxdd
  - &steamdeck-live age13gp49pwusq9lz7sld67ha02486vzn2w7wzfusapsspyuzzpureaqdmu7mu
creation_rules:
- path_regex: hosts/.*/laptop-0/.*
  key_groups:
  - pgp: [ *ccat3z ]
    age: [ *laptop-0 ]
- path_regex: hosts/.*/pc-0/.*
  key_groups:
  - pgp: [ *ccat3z ]
    age: [ *pc-0 ]
- path_regex: hosts/.*/steamdeck-live/.*
  key_groups:
  - pgp: [ *ccat3z ]
    age: [ *steamdeck-live ]
- path_regex: secrets/.*
  key_groups:
  - pgp: [ *ccat3z ]
    age: [ *laptop-0, *pc-0, *steamdeck-live ]
