creation_rules:
- path_regex: secrets/.*
  key_groups:
  - pgp:
    - A784DBF88D718B5FA46CF254040BD409F274BE67
    age:
    # qemu-laptop-0
    - age1k2nxzutadf23dkvc584h5avvcd3u3dds30zxsrep5p3tkzza59usc99jep
    # lab-0
    - age1e0t7v2m00ty7t3hrqac75tms9njp0n3422u6h6pqs36g8psk4g2q556j0d
    # laptop-0
    - age1826auh2ke2ur94hthmxyqachhxdlhg4n6unn0we6dguwjeum4efskv2n8v
    # pc-0
    - age107awdyvh40y48gjzsvnf63ev4hzj0sgpl8x4ryfzw582qkznx53smffxdd
