# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.loader.systemd-boot.enable = true;
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/f81b422e-2ac8-4184-a1e4-50b36daeb85a";
      fsType = "btrfs";
      options = [ "subvol=rootfs" ];
    };

  boot.initrd.luks.devices."root0".device = "/dev/disk/by-uuid/1c22c9fd-b730-4af0-9efe-75dcdaa806fe";

  fileSystems."/mnt/volume" =
    {
      device = "/dev/disk/by-uuid/f81b422e-2ac8-4184-a1e4-50b36daeb85a";
      fsType = "btrfs";
    };

  fileSystems."/mnt/syncthing" =
    {
      device = "/dev/disk/by-uuid/f81b422e-2ac8-4184-a1e4-50b36daeb85a";
      fsType = "btrfs";
      options = [ "subvol=syncthing" ];
    };
  system.activationScripts.chownSyncthing = ''
    chown ccat3z:${config.users.users.ccat3z.group} /mnt/syncthing
  '';

  fileSystems."/var/lib/libvirt" =
    {
      device = "/dev/disk/by-uuid/f81b422e-2ac8-4184-a1e4-50b36daeb85a";
      fsType = "btrfs";
      options = [ "subvol=libvirt" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/D05D-5377";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp58s0.useDHCP = lib.mkDefault true;
  services.proxy.enable = true;

  virtualisation.libvirtd.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  system.stateVersion = "23.11";
}
